In [6]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [8]:
! .\.venv10\Scripts\activate
from pycaret.classification import evaluate_model, tune_model, setup, compare_models, blend_models, stack_models

ModuleNotFoundError: No module named 'pycaret'

In [ ]:
data = pd.read_csv('../data/processed_smoke_detector.csv')
data.head()

,Temperature[C],Humidity[%],TVOC[ppb],eCO2[ppm],Raw H2,Raw Ethanol,Pressure[hPa],NC2.5,Fire Alarm,IsItDay?,Weekday_0,Weekday_1,Weekday_2
0,27.041,49.80,19.0,400.0,13059.0,19951,939.777,0.011,0,0,0,0,1
1,26.987,54.26,1.0,400.0,13078.0,19975,939.765,0.011,0,0,0,0,1
2,26.985,53.66,10.0,400.0,13068.0,19955,939.768,0.011,0,0,0,0,1
3,26.983,53.07,10.0,400.0,13069.0,19963,939.775,0.013,0,0,0,0,1
4,26.982,52.57,13.0,400.0,13072.0,19958,939.770,0.013,0,0,0,0,1

In [ ]:
exp = setup(data=data,
            target='Fire Alarm', 
            normalize=True, 
            train_size=0.8, 
            session_id=42)

In [ ]:
best_model = compare_models()

In [ ]:
tuned_model = tune_model(best_model)

In [ ]:
evaluate_model(tuned_model)

In [ ]:
top3_models = compare_models(n_select=3)
blended_model = blend_models(estimator_list=top3_models)
evaluate_model(blended_model)

In [ ]:
top5_models = compare_models(n_select=5)
stacked_model = stack_models(estimator_list=top5_models, meta_model=None)
evaluate_model(stacked_model)

In [ ]:
from pycaret.regression import evaluate_model, tune_model, setup, compare_models

In [ ]:
data = pd.read_csv('../data/processed_trip_duration.csv')
data.head()

,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,trip_duration,in_nyc_center?,distance,hour_1,hour_2,...,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23,hour_24,is_it_weekday?,is_it_first_vendor?(else 2nd)
0,1,-73.953918,40.778873,-73.963875,40.771164,400,1,1199.769914,1,0,...,0,0,0,0,0,0,0,0,1,0
1,2,-73.988312,40.731743,-73.994751,40.694931,1100,1,4123.945168,0,1,...,0,0,0,0,0,0,0,0,1,1
2,2,-73.997314,40.721458,-73.948029,40.774918,1635,1,7250.435807,0,0,...,0,0,0,0,0,0,0,0,0,0
3,6,-73.961670,40.759720,-73.956779,40.780628,1141,1,2358.286547,0,0,...,0,0,0,0,0,0,0,0,1,0
4,2,-73.993614,40.751884,-73.995422,40.723862,1455,1,3115.641570,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
exp = setup(data=data, 
            target='trip_duration',
            normalize=True,
            train_size=0.8, 
            session_id=42)

In [ ]:
best_model = compare_models()

In [ ]:
tuned_model = tune_model(best_model)

In [ ]:
evaluate_model(tuned_model)